In [ ]:
# Pandas Data Science Library
# Numpy --> Numerical Python

import numpy as np
import pandas as pd

print(pd.__version__)

2.2.2

In [ ]:
# numpy --> array()
arr = np.array([10, 20, 30, 40, 50])
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[10 20 30 40 50]

In [ ]:
# Pandas Series
# Series is 1D Labelled Array 0,1,2,3,4 bahagian row
# Data frame for 2D
s = pd.Series([10, 20, 30, 40, 50])
print(type(s))
print(s)
print(s.shape)

# In Numpy --> Only Numbers
# In Series --> Numbers + Labels (index)

<class 'pandas.core.series.Series'>
0    10
1    20
2    30
3    40
4    50
dtype: int64
(5,)

In [ ]:
info = pd.Series(['John', 28, 6700, 'Klang'], index = ['name', 'age', 'sal', 'city'])
print(info)
print(info['name'])      # indexing
print(info.get('city'))  # getting data values using get()
print(info.iloc[2])      # iloc --> index location

# Series is like a Dictionary + combo

name     John
age        28
sal      6700
city    Klang
dtype: object
John
Klang
6700

In [ ]:
info = {'Name':'John', 'Age':28, 'Sal':6700, 'City':'Klang'}
print(type(info))
print(info['Name'])
print(info.get('City'))
print(info[0])

<class 'dict'>
John
Klang

KeyError: 0

In [ ]:
# value property
# print only value

print(info.values)

<built-in method values of dict object at 0x78615a5cc980>

In [ ]:
# Indexing Slicing and Using For Loop
s = pd.Series([100, 200, 300, 400, 500, 600], index=['v1', 'v2', 'v3', 'v4', 'v5', 'v6'])
print(s)

# 100  200  300  400  500  600
#  0    1    2    3    4    5
# -6   -5   -4   -3   -2   -1
# v1   v2   v3   v4   v5   v6

# Indexing in Series can be done by using [] or iloc[]  or loc[]

print('\nIndexing In Series')
print(s.iloc[0])     # for index numbers
print(s.loc['v5'])   # loc used for labels
print(s['v2'])       # [] used for labels
print(s.iloc[-1])


print('\nSlicing In Series')
print(s[1:4])         # 4 will be excluded --> stopIndex
print(s['v1':'v5'])   # if performing slicing using labels, the end label is included
print(s.iloc[0:4])

# print 100 , 400 and 600 only
print(s.iloc[[0, 3, 5]])
print(s[['v1','v4','v6']])  # for specific information use s[['','','']]
print(s[['v1','v4','v6']].values)

# Conditional selection
print('\nConditional Selection')
print(s[s%3==0])
print(s[s>300])

v1    100
v2    200
v3    300
v4    400
v5    500
v6    600
dtype: int64

Indexing In Series
100
500
200
600

Slicing In Series
v2    200
v3    300
v4    400
dtype: int64
v1    100
v2    200
v3    300
v4    400
v5    500
dtype: int64
v1    100
v2    200
v3    300
v4    400
dtype: int64
v1    100
v4    400
v6    600
dtype: int64
v1    100
v4    400
v6    600
dtype: int64
[100 400 600]

Conditional Selection
v3    300
v6    600
dtype: int64
v4    400
v5    500
v6    600
dtype: int64

In [ ]:
# Using for Loop

for i in s:
  print(i)

100
200
300
400
500
600

In [ ]:
for k,v in s.items():
  print(k,v)

v1 100
v2 200
v3 300
v4 400
v5 500
v6 600

In [ ]:
for i in enumerate(s):
  print(i)

(0, 100)
(1, 200)
(2, 300)
(3, 400)
(4, 500)
(5, 600)

In [ ]:
# Panda DataFrame
# it used to display the information in a tabular fashion
# Pandas DataFrama is 2D Array

data = {
    'name':['John','Alex','Smith'],
    'dept':['IT','HR','MR'],
    'sal':[6700,5600,6000],
    'city':['KL','JB','ML']
}
print(data)

{'name': ['John', 'Alex', 'Smith'], 'dept': ['IT', 'HR', 'MR'], 'sal': [6700, 5600, 6000], 'city': ['KL', 'JB', 'ML']}

In [ ]:
df = pd.DataFrame(data)
print(df)
df

    name dept   sal city
0   John   IT  6700   KL
1   Alex   HR  5600   JB
2  Smith   MR  6000   ML

    name dept   sal city
0   John   IT  6700   KL
1   Alex   HR  5600   JB
2  Smith   MR  6000   ML

In [ ]:
print(df.shape)

(3, 4)

In [ ]:
data = {
    'Calories':[420,380,560],
    'Duration':[56,30,75]
}

df = pd.DataFrame(data, index = ['day1','day2','day3'])

print(df)
df

      Calories  Duration
day1       420        56
day2       380        30
day3       560        75

      Calories  Duration
day1       420        56
day2       380        30
day3       560        75